version: "3.7"
services:
  otel:
    image: otel/opentelemetry-collector-contrib:latest
    command: --config /otel-collector/collector-config.yml --log-level error
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - HOSTMETRICS_INTERVAL_SECS
      - LOG_GROUP_NAME
      - LOGS_NAMESPACE
      - LOG_STREAM_NAME
      - PROCESS_COMMAND_LINE
      - PROCESS_EXECUTABLE_NAME
    volumes:
      - ./otel-collector:/otel-collector
      - type: bind
        source: /proc
        target: /proc
    ports:
      - '4317:4317'
    user: "${UID}:${GID}"

  app:
    image: ${APP_IMAGE}
    environment:
      - INSTANCE_ID
      - LISTEN_ADDRESS
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION=us-west-2
      - SAMPLE_APP_LOG_LEVEL=ERROR
      - OTEL_RESOURCE_ATTRIBUTES=service.name=aws-otel-integ-test
      - OTEL_EXPORTER_OTLP_ENDPOINT=grpc://otel:4317
    ports:
      - '8080:8080'

  load-generator:
    build:
      context: ./load-generator
    environment:
      - TEST_DURATION_MINUTES
    depends_on:
      - otel
      - app

  alarms-poller:
    build:
      context: ./alarms-poller
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION=us-west-2
      - HOSTMETRICS_INTERVAL_SECS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - load-generator
